<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MoviesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('movies')->insert([
            [
                'id' => 1,
                'title' => 'Inception',
                'poster' => 'poster_inception.jpg',
                'link' => 'link_inception.com',
                'calification' => 'PG-13',
                'director' => 'Christopher Nolan',
                'characters' => 'Dom Cobb, Arthur',
                'duration' => '148 min',
                'link_video' => 'video_inception.com',
                'synopsis' => 'A mind-bending thriller about dreams.',
                'link_ticket' => 'ticket_inception.com',
            ],
            [
                'id' => 2,
                'title' => 'The Matrix',
                'poster' => 'poster_matrix.jpg',
                'link' => 'link_matrix.com',
                'calification' => 'R',
                'director' => 'Lana Wachowski',
                'characters' => 'Neo, Trinity',
                'duration' => '136 min',
                'link_video' => 'video_matrix.com',
                'synopsis' => 'A hacker discovers the truth about his reality.',
                'link_ticket' => 'ticket_matrix.com',
            ],
            [
                'id' => 3,
                'title' => 'Interstellar',
                'poster' => 'poster_interstellar.jpg',
                'link' => 'link_interstellar.com',
                'calification' => 'PG-13',
                'director' => 'Christopher Nolan',
                'characters' => 'Cooper, Murph',
                'duration' => '169 min',
                'link_video' => 'video_interstellar.com',
                'synopsis' => 'A space exploration epic.',
                'link_ticket' => 'ticket_interstellar.com',
            ],
            [
                'id' => 4,
                'title' => 'The Dark Knight',
                'poster' => 'poster_dark_knight.jpg',
                'link' => 'link_dark_knight.com',
                'calification' => 'PG-13',
                'director' => 'Christopher Nolan',
                'characters' => 'Batman, Joker',
                'duration' => '152 min',
                'link_video' => 'video_dark_knight.com',
                'synopsis' => 'Batman faces the Joker.',
                'link_ticket' => 'ticket_dark_knight.com',
            ],
            [
                'id' => 5,
                'title' => 'Avengers: Endgame',
                'poster' => 'poster_endgame.jpg',
                'link' => 'link_endgame.com',
                'calification' => 'PG-13',
                'director' => 'Russo Brothers',
                'characters' => 'Iron Man, Captain America',
                'duration' => '181 min',
                'link_video' => 'video_endgame.com',
                'synopsis' => 'The Avengers assemble to undo Thanos.',
                'link_ticket' => 'ticket_endgame.com',
            ],
            [
                'id' => 6,
                'title' => 'Titanic',
                'poster' => 'poster_titanic.jpg',
                'link' => 'link_titanic.com',
                'calification' => 'PG-13',
                'director' => 'James Cameron',
                'characters' => 'Jack, Rose',
                'duration' => '195 min',
                'link_video' => 'video_titanic.com',
                'synopsis' => 'A tragic love story on the Titanic.',
                'link_ticket' => 'ticket_titanic.com',
            ],
            [
                'id' => 7,
                'title' => 'Joker',
                'poster' => 'poster_joker.jpg',
                'link' => 'link_joker.com',
                'calification' => 'R',
                'director' => 'Todd Phillips',
                'characters' => 'Arthur Fleck',
                'duration' => '122 min',
                'link_video' => 'video_joker.com',
                'synopsis' => 'A deep dive into the Joker’s origins.',
                'link_ticket' => 'ticket_joker.com',
            ],
            [
                'id' => 8,
                'title' => 'Toy Story',
                'poster' => 'poster_toy_story.jpg',
                'link' => 'link_toy_story.com',
                'calification' => 'G',
                'director' => 'John Lasseter',
                'characters' => 'Woody, Buzz',
                'duration' => '81 min',
                'link_video' => 'video_toy_story.com',
                'synopsis' => 'Toys come to life in this animated classic.',
                'link_ticket' => 'ticket_toy_story.com',
            ],
            [
                'id' => 9,
                'title' => 'The Lion King',
                'poster' => 'poster_lion_king.jpg',
                'link' => 'link_lion_king.com',
                'calification' => 'G',
                'director' => 'Rob Minkoff',
                'characters' => 'Simba, Mufasa',
                'duration' => '88 min',
                'link_video' => 'video_lion_king.com',
                'synopsis' => 'The story of Simba, the lion prince.',
                'link_ticket' => 'ticket_lion_king.com',
            ],
            [
                'id' => 10,
                'title' => 'Frozen',
                'poster' => 'poster_frozen.jpg',
                'link' => 'link_frozen.com',
                'calification' => 'PG',
                'director' => 'Chris Buck',
                'characters' => 'Elsa, Anna',
                'duration' => '102 min',
                'link_video' => 'video_frozen.com',
                'synopsis' => 'An icy adventure of two sisters.',
                'link_ticket' => 'ticket_frozen.com',
            ],
            [
                'id' => 11,
                'title' => 'Shrek',
                'poster' => 'poster_shrek.jpg',
                'link' => 'link_shrek.com',
                'calification' => 'PG',
                'director' => 'Andrew Adamson',
                'characters' => 'Shrek, Donkey',
                'duration' => '90 min',
                'link_video' => 'video_shrek.com',
                'synopsis' => 'An ogre’s journey to save a princess.',
                'link_ticket' => 'ticket_shrek.com',
            ],
            [
                'id' => 12,
                'title' => 'Finding Nemo',
                'poster' => 'poster_nemo.jpg',
                'link' => 'link_nemo.com',
                'calification' => 'G',
                'director' => 'Andrew Stanton',
                'characters' => 'Nemo, Dory',
                'duration' => '100 min',
                'link_video' => 'video_nemo.com',
                'synopsis' => 'A father’s journey to find his son.',
                'link_ticket' => 'ticket_nemo.com',
            ],
            [
                'id' => 13,
                'title' => 'Harry Potter',
                'poster' => 'poster_harry_potter.jpg',
                'link' => 'link_harry_potter.com',
                'calification' => 'PG-13',
                'director' => 'Chris Columbus',
                'characters' => 'Harry, Hermione',
                'duration' => '152 min',
                'link_video' => 'video_harry_potter.com',
                'synopsis' => 'A young wizard’s journey begins.',
                'link_ticket' => 'ticket_harry_potter.com',
            ],
            [
                'id' => 14,
                'title' => 'Spider-Man: No Way Home',
                'poster' => 'poster_spiderman.jpg',
                'link' => 'link_spiderman.com',
                'calification' => 'PG-13',
                'director' => 'Jon Watts',
                'characters' => 'Spider-Man, Doctor Strange',
                'duration' => '148 min',
                'link_video' => 'video_spiderman.com',
                'synopsis' => 'Spider-Man faces multiverse chaos.',
                'link_ticket' => 'ticket_spiderman.com',
            ],
            [
                'id' => 15,
                'title' => 'Black Panther',
                'poster' => 'poster_black_panther.jpg',
                'link' => 'link_black_panther.com',
                'calification' => 'PG-13',
                'director' => 'Ryan Coogler',
                'characters' => 'T’Challa, Shuri',
                'duration' => '134 min',
                'link_video' => 'video_black_panther.com',
                'synopsis' => 'A king rises to protect Wakanda.',
                'link_ticket' => 'ticket_black_panther.com',
            ],
        ]);
    }
}
