name: Deploy to Server

on:
  push:
    branches:
      - main  # Solo se ejecuta cuando hay un push a main
  pull_request:
    types:
      - closed  # Solo se ejecutará cuando el Pull Request se cierre (normalmente tras un merge)
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Directorio local a subir
        server-dir: /api-avila-digital/  # Ruta en el servidor
